name: "Hello Action"
description: "Hello nice to meet you"
author: "sjuliper7@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    defult: "World!"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"